"""One FastAPI entrypoint for corpus ingestion, evidence and agent streaming."""

import asyncio
import json
import logging
import os
import shutil
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Literal
from uuid import uuid4

from fastapi import FastAPI, File, HTTPException, Request, Response, UploadFile
from fastapi.responses import FileResponse, JSONResponse, StreamingResponse
from pydantic import BaseModel, ConfigDict, Field

from .agent.config import DOX_AGENT_ROOT, get_settings
from .agent.corpora import (
    DB_DIRNAME,
    SOURCE_DIRNAME,
    SOURCE_SUFFIXES,
    VECTOR_DIRNAME,
    CorpusInfo,
    corpus_id_for,
    corpus_root_for,
    default_corpus_info,
    load_corpus_overrides,
    migrate_layout,
    rewrite_origins,
    save_corpus_overrides,
    scan_corpora,
    valid_corpus_name,
)
from .agent.graph import build_graph
from .agent.models import tracing
from .agent.usage import TurnUsage
from .knowledge import Knowledge
from .official_docs import import_official
from .parsers import import_defaults, parse_web
from .prompts import list_tasks
from .reports import ReportStore, generate_markdown
from .retrieval import fit_history
from .workspace import Workspace
from .workspace import router as workspace_router

logger = logging.getLogger(__name__)

FILE_MEDIA_TYPES = {".pdf": "application/pdf", ".md": "text/markdown", ".markdown": "text/markdown", ".txt": "text/plain"}
MAX_PREVIEW_BYTES = 200 * 1024 * 1024


def local_path_in_roots(origin: str, settings) -> tuple[Path, str] | None:
    """D3: resolve a stored origin to ``(file, corpus-relative path)``, only inside a configured root.

    Web and manual origins have no file; anything outside the roots is refused, so a stored
    origin can never be turned into an arbitrary filesystem read.
    """
    if "://" in origin or origin.startswith("manual:"):
        return None
    try:
        path = Path(origin).resolve()
    except OSError:
        return None
    # H1/§10: raw corpora live under CORPORA_ROOT (default .knowledge); single allowed root.
    root = Path(settings.corpora_root).resolve()
    try:
        return path, path.relative_to(root).as_posix()
    except ValueError:
        return None


class ChatMessage(BaseModel):
    model_config = ConfigDict(extra="forbid")
    role: Literal["user", "assistant"]
    content: str = Field(min_length=1, max_length=12000)


class ChatRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    messages: list[ChatMessage] = Field(min_length=1, max_length=20)
    allowed_doc_ids: list[str] | None = Field(default=None, min_length=1, max_length=20)
    # task4 is allowed for free-text intake; its report body is generated by POST /api/reports.
    task_id: Literal["task1", "task2", "task3", "task4"] = "task1"
    # H4: optional corpus binding; absent = the default corpus (backward compatible).
    corpus_id: str | None = Field(default=None, min_length=1, max_length=120)
    run_id: str = Field(default_factory=lambda: uuid4().hex, min_length=8, max_length=80)


class ReportRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    domain: str = Field(min_length=1, max_length=120)
    year_from: int = Field(ge=1900, le=2100)
    year_to: int = Field(ge=1900, le=2100)
    template_id: Literal["achievements", "hotspots", "future_directions", "comprehensive"]
    fund_type: str = Field(default="", max_length=120)
    focus: str = Field(default="", max_length=2000)
    doc_ids: list[str] | None = Field(default=None, min_length=1, max_length=20)
    corpus_id: str | None = Field(default=None, min_length=1, max_length=120)
    session_key: str | None = Field(default=None, max_length=120)
    run_id: str | None = Field(default=None, max_length=80)


class WebRequest(BaseModel):
    url: str = Field(min_length=1, max_length=4000)


class OfficialRequest(BaseModel):
    sections: list[Literal["langchain", "langgraph", "deepagents"]] = Field(default=["langchain", "langgraph", "deepagents"], min_length=1, max_length=3)


class CorpusCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: str = Field(min_length=1, max_length=80)


class CorpusRename(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: str = Field(min_length=1, max_length=80)


class FileRename(BaseModel):
    model_config = ConfigDict(extra="forbid")
    rel_path: str = Field(min_length=1, max_length=1000)
    new_name: str = Field(min_length=1, max_length=255)


def workspace_path(settings, knowledge) -> Path:
    """K0: keep sessions/notes in the app-level ``state_dir``, independent of the active corpus.

    One-time migration copies a legacy ``<corpus>/datadb/workspace.sqlite3`` if the app-level
    file does not exist yet, so history survives the move.
    """
    target = settings.state_dir / "workspace.sqlite3"
    legacy = knowledge.path.parent / "workspace.sqlite3"
    if not target.exists() and legacy.exists():
        try:
            if legacy.resolve() != target.resolve():
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(legacy, target)
        except OSError:
            pass
    return target


def sse(event: str, data: object) -> str:
    return f"event: {event}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n"


def create_app(settings=None, knowledge=None, graph_factory=build_graph):
    settings = settings or get_settings()

    @asynccontextmanager
    async def lifespan(app):
        for line in await asyncio.to_thread(migrate_layout, settings):
            logger.info("layout migration: %s", line)
        info = await asyncio.to_thread(default_corpus_info, settings)
        db_path = info.db_dir / "knowledge.sqlite3" if info else Path(settings.state_dir) / "knowledge.sqlite3"
        app.state.knowledge = knowledge or Knowledge(
            db_path, settings=settings, vectordb_dir=info.vectordb_dir if info else None)
        app.state.workspace = Workspace(workspace_path(settings, app.state.knowledge))
        app.state.knowledge.workspace = app.state.workspace
        app.state.reports = ReportStore(settings.state_dir / "reports.sqlite3")
        app.state.import_lock = asyncio.Lock()
        app.state.preview = None
        app.state.official_job = {"status": "idle", "total": 0, "completed": 0, "imported": 0, "changed": 0, "errors": []}
        app.state.official_task = None
        # H1/H2: per-corpus Knowledge cache (default corpus reuses app.state.knowledge),
        # ingest job states and their tasks.
        app.state.corpus_knowledge = {}
        app.state.corpus_jobs = {}
        app.state.corpus_tasks = {}
        app.state.preparation = "ready" if knowledge is not None else "running"

        async def prepare():
            if knowledge is not None:
                return
            try:
                if settings.auto_import_official and not any(doc["kind"] == "official" for doc in await asyncio.to_thread(app.state.knowledge.all)):
                    async with app.state.import_lock:
                        app.state.official_job["status"] = "running"
                        await import_official(app.state.knowledge, ["langchain", "langgraph", "deepagents"], app.state.official_job)
                        app.state.official_job["status"] = "partial" if app.state.official_job["errors"] else "done"
                if app.state.knowledge.dense and settings.warmup_query.strip():
                    await asyncio.to_thread(app.state.knowledge.search, settings.warmup_query.strip())
                if not await asyncio.to_thread(app.state.knowledge.count):
                    raise RuntimeError("No documents available after preparation")
                app.state.preparation = "ready"
            except Exception as exc:
                logger.exception("Background preparation failed")
                if app.state.official_job["status"] == "running":
                    app.state.official_job["status"] = "error"
                    app.state.official_job["errors"].append({"error": type(exc).__name__})
                app.state.preparation = "error"

        preparation_task = asyncio.create_task(prepare())
        yield
        preparation_task.cancel()
        await asyncio.gather(preparation_task, return_exceptions=True)
        if app.state.official_task and not app.state.official_task.done():
            app.state.official_task.cancel()
            await asyncio.gather(app.state.official_task, return_exceptions=True)
        for corpus_task in app.state.corpus_tasks.values():
            if not corpus_task.done():
                corpus_task.cancel()
        if app.state.corpus_tasks:
            await asyncio.gather(*app.state.corpus_tasks.values(), return_exceptions=True)

    app = FastAPI(title="dox_agent", version="0.2.0", lifespan=lifespan)

    app.include_router(workspace_router)

    def find_corpus(corpus_id: str) -> CorpusInfo | None:
        for info in scan_corpora(settings):
            if info.id == corpus_id:
                return info
        return None

    def knowledge_for(info: CorpusInfo) -> Knowledge:
        """Lazy per-corpus Knowledge; the default corpus reuses the lifespan instance."""
        if info.is_default:
            return app.state.knowledge
        cached = app.state.corpus_knowledge.get(info.id)
        if cached is None:
            # 方案 A: derived data stays inside the corpus dir (datadb/ + vectordb/), never
            # in source/; a non-default corpus gets its own vector directory.
            cached = Knowledge(info.sqlite or info.db_dir / "knowledge.sqlite3", settings=settings,
                               vectordb_dir=info.vectordb_dir)
            app.state.corpus_knowledge[info.id] = cached
        return cached

    async def knowledge_for_request(corpus: str | None) -> Knowledge:
        """Resolve the corpus for read/file; absent = the default corpus (K0b)."""
        if corpus is None:
            return app.state.knowledge
        info = await asyncio.to_thread(find_corpus, corpus)
        if info is None:
            raise HTTPException(404, "知识库不存在")
        return knowledge_for(info)

    @app.get("/api/health")
    async def health(request: Request):
        docs_count = await asyncio.to_thread(request.app.state.knowledge.count)
        default_info = await asyncio.to_thread(default_corpus_info, settings)
        return {
            "status": "ok",
            "app_id": "dox-agent",
            "model": settings.model_name,
            "docs_count": docs_count,
            "api_key_configured": bool(settings.model_api_key),
            "model_verified": False,
            "web_provider": settings.web_provider,
            "preparation": request.app.state.preparation,
            "corpus_id": default_info.id if default_info else "",
            "index_progress": request.app.state.knowledge.dense.progress if request.app.state.knowledge.dense else None,
        }

    @app.get("/api/tasks")
    async def tasks():
        return list_tasks()

    def corpus_payload(info: CorpusInfo) -> dict:
        dense = app.state.knowledge.dense
        return {
            "id": info.id,
            "name": info.name,
            "kind": info.kind,
            "domain": info.domain,
            "rel_path": info.rel_path,
            "docs_count": info.docs_count,
            "preparation": info.preparation,
            "is_default": info.is_default,
            "alias": info.alias,
            "dir_name": info.dir_name or info.root.name,
            "index_progress": dense.progress if info.is_default and dense else None,
            "job": app.state.corpus_jobs.get(info.id),
        }

    @app.get("/api/corpora")
    async def corpora():
        """H1: corpus registry — disk scan + config/override names, read-only."""
        items = await asyncio.to_thread(scan_corpora, settings)
        return [corpus_payload(info) for info in items]

    @app.post("/api/corpora", status_code=201)
    async def create_corpus(payload: CorpusCreate):
        """K6: create a new self-contained corpus directory (source/datadb/vectordb)."""
        name = payload.name.strip()
        root = corpus_root_for(settings)
        target = (root / name).resolve()
        if not valid_corpus_name(name) or not target.is_relative_to(root.resolve()):
            raise HTTPException(422, "知识库名称非法")
        if target.exists():
            raise HTTPException(409, "同名知识库已存在")
        def create_dirs():
            for role in (SOURCE_DIRNAME, DB_DIRNAME, VECTOR_DIRNAME):
                (target / role).mkdir(parents=True, exist_ok=True)
            corpus_id = corpus_id_for(name)
            overrides = load_corpus_overrides(settings)
            overrides[corpus_id] = {"id": corpus_id, "rel": name, "alias": "", "created": True}
            save_corpus_overrides(settings, overrides)

        await asyncio.to_thread(create_dirs)
        items = await asyncio.to_thread(scan_corpora, settings)
        info = next((item for item in items if item.rel_path == name), None)
        if info is None:
            raise HTTPException(500, "知识库创建后未能扫描到")
        return corpus_payload(info)

    @app.patch("/api/corpora/{corpus_id}")
    async def rename_corpus(request: Request, payload: CorpusRename, corpus_id: str):
        """KB-5b: rename syncs ``.knowledge/<dir>``; stable corpus_id and doc ids are kept."""
        name = payload.name.strip()
        if not valid_corpus_name(name):
            raise HTTPException(422, "知识库名称非法")
        info = await asyncio.to_thread(find_corpus, corpus_id)
        if info is None:
            raise HTTPException(404, "知识库不存在")
        root = corpus_root_for(settings)
        target = (root / name).resolve()
        if not target.is_relative_to(root) or target.exists():
            raise HTTPException(409, "同名知识库已存在")
        running = request.app.state.corpus_tasks.get(corpus_id)
        if running and not running.done():
            raise HTTPException(409, "该知识库正在导入")
        old = info.root

        def do_rename():
            if old.name.lower() == name.lower():
                # Case-only rename: two-step so a case-insensitive FS does not see a conflict (T5).
                temp = root / (".rename-" + uuid4().hex)
                os.rename(old, temp)
                os.rename(temp, target)
            else:
                os.rename(old, target)
            try:
                # T1/T2: rewrite file-type origins but keep doc ids; DB write is transactional.
                rewrite_origins(target / DB_DIRNAME / "knowledge.sqlite3", old, target, [])
            except Exception:
                os.rename(target, old)  # roll back the directory
                raise
            overrides = load_corpus_overrides(settings)
            entry = overrides.get(corpus_id, {})
            # Renaming syncs the display name to the directory name, so the old alias is cleared.
            overrides[corpus_id] = {**entry, "id": corpus_id, "rel": name, "alias": ""}
            save_corpus_overrides(settings, overrides)

        async with request.app.state.import_lock:
            await asyncio.to_thread(do_rename)
        app.state.corpus_knowledge.pop(corpus_id, None)
        items = await asyncio.to_thread(scan_corpora, settings)
        return corpus_payload(next(item for item in items if item.id == corpus_id))

    @app.delete("/api/corpora/{corpus_id}")
    async def delete_corpus(corpus_id: str, purge_source: bool = False):
        """K6: delete derived data by default; ``purge_source=true`` also removes source files."""
        info = await asyncio.to_thread(find_corpus, corpus_id)
        if info is None:
            raise HTTPException(404, "知识库不存在")
        if info.is_default:
            raise HTTPException(409, "不能删除当前活动（默认）知识库")

        def remove():
            shutil.rmtree(info.db_dir, ignore_errors=True)
            shutil.rmtree(info.vectordb_dir, ignore_errors=True)
            if purge_source:
                shutil.rmtree(info.root, ignore_errors=True)
            elif info.root.exists() and not any(info.root.iterdir()):
                shutil.rmtree(info.root, ignore_errors=True)
            overrides = load_corpus_overrides(settings)
            if corpus_id in overrides:
                overrides.pop(corpus_id)
                save_corpus_overrides(settings, overrides)

        await asyncio.to_thread(remove)
        app.state.corpus_knowledge.pop(corpus_id, None)
        return {"deleted": corpus_id, "purged_source": purge_source}

    @app.post("/api/corpora/{corpus_id}/ingest", status_code=202)
    async def corpus_ingest(request: Request, corpus_id: str, force: bool = False):
        """H2/K13: import one corpus; ``force`` re-parses everything (e.g. after a parser change)."""
        info = await asyncio.to_thread(find_corpus, corpus_id)
        if info is None:
            raise HTTPException(404, "知识库不存在")
        running = request.app.state.corpus_tasks.get(corpus_id)
        if running and not running.done():
            raise HTTPException(409, "该知识库正在导入")
        job = {"status": "running", "total": 0, "completed": 0, "imported": 0, "changed": 0,
               "added": 0, "updated": 0, "skipped": 0, "deleted": 0, "forced": force, "errors": []}
        request.app.state.corpus_jobs[corpus_id] = job

        async def run():
            try:
                async with request.app.state.import_lock:
                    kn = knowledge_for(info)
                    report = await asyncio.to_thread(import_defaults, kn, settings, root=info.source_dir,
                                                     force=force, parsed_root=info.root / "parsed")
                job["total"] = job["completed"] = report["scanned"]
                job["imported"] = len(report["imported"])
                job["changed"] = report["added"] + report["updated"]
                job["added"] = report["added"]
                job["updated"] = report["updated"]
                job["skipped"] = report["skipped"]
                job["deleted"] = report["deleted"]
                job["errors"] = report["errors"]
                job["status"] = "partial" if job["errors"] else "done"
            except Exception as exc:
                logger.exception("Corpus ingest failed")
                job["status"] = "error"
                job["errors"].append({"error": type(exc).__name__})

        request.app.state.corpus_tasks[corpus_id] = asyncio.create_task(run())
        return job

    def source_file(info: CorpusInfo, rel_path: str) -> Path:
        target = (info.source_dir / rel_path).resolve()
        if not target.is_relative_to(info.source_dir.resolve()) or not target.is_file():
            raise HTTPException(404, "文件不存在")
        return target

    def safe_file_name(name: str) -> str:
        name = Path(name or "").name.strip()
        if not name or name.startswith(".") or name in {".", ".."}:
            raise HTTPException(422, "文件名非法")
        if Path(name).suffix.lower() not in SOURCE_SUFFIXES:
            raise HTTPException(415, "仅支持 md/markdown/txt/pdf/docx")
        return name

    async def import_corpus(info: CorpusInfo, force: bool = False) -> dict:
        async with app.state.import_lock:
            return await asyncio.to_thread(import_defaults, knowledge_for(info), settings, root=info.source_dir,
                                           force=force, parsed_root=info.root / "parsed")

    @app.get("/api/corpora/{corpus_id}/files")
    async def corpus_files(corpus_id: str):
        """K7: source files with manifest status (new/indexed/error/removed)."""
        info = await asyncio.to_thread(find_corpus, corpus_id)
        if info is None:
            raise HTTPException(404, "知识库不存在")
        manifest = await asyncio.to_thread(knowledge_for(info).files)

        def listing():
            on_disk = {path.relative_to(info.source_dir).as_posix(): path
                       for path in info.source_dir.rglob("*") if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES}
            items = []
            for rel, path in sorted(on_disk.items()):
                entry = manifest.get(rel)
                items.append({"rel_path": rel, "size": path.stat().st_size,
                              "status": entry["status"] if entry else "new", "doc_id": entry["doc_id"] if entry else None})
            for rel, entry in sorted(manifest.items()):
                if rel not in on_disk:
                    items.append({"rel_path": rel, "size": entry["size"], "status": "removed", "doc_id": entry["doc_id"]})
            return items

        return {"source_dir": str(info.source_dir), "files": await asyncio.to_thread(listing)}

    @app.post("/api/corpora/{corpus_id}/files", status_code=201)
    async def upload_corpus_file(corpus_id: str, upload: UploadFile = File(...)):
        """K7: stream an md/pdf/txt into ``source/`` then import incrementally."""
        info = await asyncio.to_thread(find_corpus, corpus_id)
        if info is None:
            raise HTTPException(404, "知识库不存在")
        name = safe_file_name(upload.filename or "")
        target = (info.source_dir / name).resolve()
        if not target.is_relative_to(info.source_dir.resolve()):
            raise HTTPException(422, "文件名非法")

        def save() -> None:
            info.source_dir.mkdir(parents=True, exist_ok=True)
            written = 0
            try:
                with target.open("wb") as handle:
                    while True:
                        chunk = upload.file.read(1 << 20)
                        if not chunk:
                            break
                        written += len(chunk)
                        if written > MAX_PREVIEW_BYTES:
                            raise ValueError("文件过大，超过预览/上传上限")
                        handle.write(chunk)
            except ValueError:
                target.unlink(missing_ok=True)
                raise

        try:
            await asyncio.to_thread(save)
        except ValueError as exc:
            raise HTTPException(413, str(exc)) from exc
        report = await import_corpus(info)
        return {"rel_path": name, "added": report["added"], "updated": report["updated"],
                "skipped": report["skipped"], "deleted": report["deleted"], "errors": report["errors"]}

    @app.delete("/api/corpora/{corpus_id}/files")
    async def delete_corpus_file(corpus_id: str, rel_path: str):
        """K7: remove a source file and its indexed document."""
        info = await asyncio.to_thread(find_corpus, corpus_id)
        if info is None:
            raise HTTPException(404, "知识库不存在")
        target = await asyncio.to_thread(source_file, info, rel_path)
        await asyncio.to_thread(target.unlink)
        doc_id = await asyncio.to_thread(knowledge_for(info).drop_file, rel_path)
        return {"rel_path": rel_path, "doc_id": doc_id}

    @app.patch("/api/corpora/{corpus_id}/files")
    async def rename_corpus_file(corpus_id: str, payload: FileRename):
        """K7: rename a source file and re-index under the new path."""
        info = await asyncio.to_thread(find_corpus, corpus_id)
        if info is None:
            raise HTTPException(404, "知识库不存在")
        old = await asyncio.to_thread(source_file, info, payload.rel_path)
        new_name = safe_file_name(payload.new_name)
        new = (info.source_dir / new_name).resolve()
        if not new.is_relative_to(info.source_dir.resolve()):
            raise HTTPException(422, "文件名非法")
        if new.exists():
            raise HTTPException(409, "同名文件已存在")
        await asyncio.to_thread(old.rename, new)
        await asyncio.to_thread(knowledge_for(info).drop_file, payload.rel_path)
        report = await import_corpus(info)
        return {"rel_path": new_name, "added": report["added"], "updated": report["updated"],
                "skipped": report["skipped"], "deleted": report["deleted"], "errors": report["errors"]}

    @app.get("/api/documents")
    async def documents(request: Request, corpus: str | None = None):
        # H3: optional corpus filter; absent = default corpus (backward compatible).
        kn = request.app.state.knowledge
        if corpus is not None:
            info = await asyncio.to_thread(find_corpus, corpus)
            if info is None:
                raise HTTPException(404, "知识库不存在")
            if info.is_default:
                kn = request.app.state.knowledge
            elif info.sqlite is None:
                return []  # uninitialized corpus: read-only listing, never creates the sqlite
            else:
                kn = knowledge_for(info)
        docs = await asyncio.to_thread(kn.all)
        # D1: additive fields only. `status` is always "indexed" because this list is the corpus;
        # `meta` stays empty until stage B adds report metadata (B2/B3), so the frontend tree
        # can already be built from `rel_path` without a second endpoint.
        enriched = []
        for doc in docs:
            local = local_path_in_roots(doc["origin"], settings)
            enriched.append(
                {k: v for k, v in doc.items() if k not in ("pages", "page_count")}
                | {
                    "pages": doc["page_count"],
                    "rel_path": local[1] if local else "",
                    "status": "indexed",
                    "meta": {},
                }
            )
        return enriched

    @app.get("/api/documents/{doc_id}/file")
    async def document_file(request: Request, doc_id: str, version: str | None = None, corpus: str | None = None):
        """D2: raw PDF/Markdown/txt for the browser reader; Range is handled by FileResponse."""
        kn = await knowledge_for_request(corpus)
        try:
            doc = await asyncio.to_thread(kn.get, doc_id)
        except KeyError as exc:
            raise HTTPException(404, "文档不存在") from exc
        if version and version != doc["version"]:
            raise HTTPException(422, "文档已更新，请重新搜索")
        resolved = local_path_in_roots(doc["origin"], settings)
        path = resolved[0] if resolved else None
        if path is None or not path.is_file():
            raise HTTPException(404, "该文档不是报告根目录内的本地文件，或原文已被移动")
        media_type = FILE_MEDIA_TYPES.get(path.suffix.lower())
        if media_type is None:
            raise HTTPException(415, "该文件类型不支持网页预览")
        if path.stat().st_size > MAX_PREVIEW_BYTES:
            raise HTTPException(413, "文件过大，无法在网页内预览")
        # Inline so the raw reader (iframe/PDF viewer) renders instead of downloading.
        return FileResponse(path, media_type=media_type, filename=path.name, content_disposition_type="inline")

    @app.get("/api/documents/{doc_id}/markdown")
    async def document_markdown(request: Request, doc_id: str, version: str | None = None, corpus: str | None = None):
        """L1: parsed markdown body for rendering previews — no 300-char line splits or line windows."""
        kn = await knowledge_for_request(corpus)
        try:
            doc = await asyncio.to_thread(kn.get, doc_id)
        except KeyError as exc:
            raise HTTPException(404, "文档不存在") from exc
        if version and version != doc["version"]:
            raise HTTPException(422, "文档已更新，请重新搜索")
        text = await asyncio.to_thread(kn.read_markdown, doc_id)
        return {"text": text, "version": doc["version"]}

    @app.get("/api/official-docs")
    async def official_status():
        return app.state.official_job

    @app.post("/api/official-docs", status_code=202)
    async def official_import(payload: OfficialRequest):
        if app.state.preparation == "running":
            raise HTTPException(409, "知识库正在初始化，请等待初始化结束后更新")
        if app.state.official_task and not app.state.official_task.done():
            raise HTTPException(409, "官方文档正在更新")
        progress = {"status": "running", "total": 0, "completed": 0, "imported": 0, "changed": 0, "errors": []}
        app.state.official_job = progress

        async def run():
            try:
                async with app.state.import_lock:
                    await import_official(app.state.knowledge, payload.sections, progress)
                progress["status"] = "partial" if progress["errors"] else "done"
            except Exception as exc:
                logger.exception("Official documentation import failed")
                progress["status"] = "error"
                progress["errors"].append({"error": type(exc).__name__})

        app.state.official_task = asyncio.create_task(run())
        return progress

    @app.get("/api/documents/{doc_id}")
    async def read_document(
        request: Request, doc_id: str, page: int = 1, start_line: int = 1, version: str | None = None,
        section: bool = False, corpus: str | None = None,
    ):
        kn = await knowledge_for_request(corpus)
        try:
            return await asyncio.to_thread(
                (kn.read_section if section else kn.read), doc_id, page, start_line, 60, version
            )
        except KeyError as exc:
            raise HTTPException(404, "文档不存在") from exc
        except ValueError as exc:
            raise HTTPException(422, str(exc)) from exc

    @app.post("/api/ingest/local")
    async def ingest(request: Request):
        if app.state.preparation == "running":
            raise HTTPException(409, "知识库正在初始化，请稍后导入")
        # §10/M5: import the default corpus ``source/`` (single root, no sibling exclusion).
        info = await asyncio.to_thread(default_corpus_info, settings)
        if info is None:
            raise HTTPException(409, "没有可导入的默认知识库")
        async with app.state.import_lock:
            return await asyncio.to_thread(import_defaults, app.state.knowledge, settings,
                                           root=info.source_dir, parsed_root=info.root / "parsed")

    @app.post("/api/web/preview")
    async def preview(payload: WebRequest):
        try:
            doc = await parse_web(payload.url, settings)
            import uuid

            preview_id = uuid.uuid4().hex
            # Single-user app: only latest preview retained, not arbitrary browser-supplied content.
            app.state.preview = (preview_id, doc)
            return {"preview_id": preview_id, **doc.model_dump()}
        except (ValueError, TimeoutError) as exc:
            raise HTTPException(422, str(exc) or "网页抓取超时") from exc
        except Exception as exc:
            logger.warning("web preview failed: %s", type(exc).__name__)
            raise HTTPException(502, "抓取失败，请检查解析器安装、会话或网站访问权限") from exc

    @app.post("/api/web/confirm/{preview_id}")
    async def confirm(preview_id: str):
        if app.state.preparation == "running":
            raise HTTPException(409, "知识库正在初始化，请稍后确认")
        async with app.state.import_lock:
            current = app.state.preview
            if current is None or current[0] != preview_id:
                raise HTTPException(409, "预览已失效，请重新抓取")
            result = await asyncio.to_thread(app.state.knowledge.put, current[1])
            app.state.preview = None
            return result

    @app.post("/api/chat")
    async def chat(payload: ChatRequest, request: Request):
        if payload.messages[-1].role != "user":
            raise HTTPException(422, "最后一条消息必须来自用户")
        if sum(len(m.content) for m in payload.messages) > 40000:
            raise HTTPException(422, "对话上下文超过4万字符，请新建对话")
        # H4: optional corpus binding; absent = default corpus (backward compatible).
        # The graph and the allowed_doc_ids validation both run against this instance,
        # so retrieval can never cross corpora. Each corpus uses its own vectordb_dir,
        # so a non-default corpus also builds its own dense index when EMBEDDING_PATH is set.
        chat_knowledge = app.state.knowledge
        chat_preparation = app.state.preparation
        chat_domain = ""
        if payload.corpus_id is not None:
            info = await asyncio.to_thread(find_corpus, payload.corpus_id)
            if info is None:
                raise HTTPException(404, "知识库不存在")
            chat_knowledge = knowledge_for(info)
            chat_preparation = app.state.preparation if info.is_default else info.preparation
            chat_domain = info.domain
        else:
            default_info = await asyncio.to_thread(default_corpus_info, settings)
            chat_domain = default_info.domain if default_info else ""

        async def stream():
            policy = None
            usage = TurnUsage(settings.max_model_calls)
            try:
                async with asyncio.timeout(settings.run_timeout):
                    graph = graph_factory(chat_knowledge, settings)
                    with tracing(settings):
                        async for event in graph.astream(
                            {
                                "messages": fit_history([m.model_dump() for m in payload.messages], settings.history_tokens),
                                "rounds": 0,
                                "evidence": [],
                                "searches": {},
                                "report": None,
                                "blocked": None,
                                "runtime_usage": usage,
                                "preparation": chat_preparation,
                                "corpus_domain": chat_domain,
                                "task_id": payload.task_id,
                                "options": {"allowed_doc_ids": payload.allowed_doc_ids},
                            },
                            stream_mode="custom",
                            config={"recursion_limit": 12, "tags": ["dox-agent", "agentic-rag"], "callbacks": [usage]},
                        ):
                            if await request.is_disconnected():
                                return
                            if event["event"] == "policy":
                                policy = event["data"]
                            data = event["data"]
                            if event["event"] in {"step", "telemetry"}:
                                data = {**data, "run_id": payload.run_id}
                            yield sse(event["event"], data)
                            if event["event"] == "telemetry":
                                yield sse("usage", {**usage.snapshot(), "run_id": payload.run_id})
                    yield sse("usage", {**usage.snapshot(), "run_id": payload.run_id})
                    yield sse("done", {"ok": True})
            except asyncio.CancelledError:
                raise
            except ValueError as exc:
                yield sse("usage", {**usage.snapshot(), "run_id": payload.run_id})
                if policy:
                    yield sse("policy", {**policy, "stop_reason": "invalid_request"})
                yield sse("error", {"message": str(exc)})
            except TimeoutError:
                yield sse("usage", {**usage.snapshot(), "run_id": payload.run_id})
                if policy:
                    yield sse("policy", {**policy, "stop_reason": "timed_out"})
                yield sse("error", {"message": "运行达到时间预算，请缩小问题范围"})
            except Exception as exc:  # noqa: BLE001 - API boundary hides provider secrets
                yield sse("usage", {**usage.snapshot(), "run_id": payload.run_id})
                logger.warning("chat failed: %s", type(exc).__name__)
                if policy:
                    yield sse("policy", {**policy, "stop_reason": "failed"})
                yield sse("error", {"message": "问答未完成，请检查模型配置或稍后重试"})

        return StreamingResponse(
            stream(),
            media_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
        )

    @app.get("/api/reports")
    async def list_reports(session_key: str | None = None, run_id: str | None = None, limit: int = 20):
        """#10: report metadata for a session (no markdown), newest first."""
        return await asyncio.to_thread(app.state.reports.list,
                                       session_key=session_key, run_id=run_id, limit=limit)

    @app.post("/api/reports")
    async def create_report(payload: ReportRequest):
        if payload.year_from > payload.year_to:
            raise HTTPException(422, "起始年份不能晚于结束年份")
        kn = await knowledge_for_request(payload.corpus_id)
        session_key = payload.session_key or ""
        if payload.run_id:  # M3: idempotent per (session_key, run_id)
            existing = await asyncio.to_thread(app.state.reports.find, session_key, payload.run_id)
            if existing is not None:
                return JSONResponse({**existing, "idempotent": True}, status_code=200)
        try:
            markdown = await generate_markdown(kn, settings, payload.model_dump())
        except ValueError as exc:
            raise HTTPException(422, str(exc)) from exc
        report_id = uuid4().hex
        await asyncio.to_thread(app.state.reports.save, report_id, payload.model_dump(), markdown,
                                session_key=session_key, run_id=payload.run_id or "",
                                corpus_id=payload.corpus_id or "")
        return JSONResponse({"report_id": report_id, "params": payload.model_dump(), "markdown": markdown,
                             "idempotent": False}, status_code=201)

    @app.get("/api/reports/{report_id}")
    async def get_report(report_id: str):
        try:
            return await asyncio.to_thread(app.state.reports.get, report_id)
        except KeyError as exc:
            raise HTTPException(404, "报告不存在") from exc

    @app.get("/api/reports/{report_id}/export")
    async def export_report(report_id: str, format: str = "md"):
        if format != "md":
            raise HTTPException(422, "首期仅支持 md 导出")
        try:
            report = await asyncio.to_thread(app.state.reports.get, report_id)
        except KeyError as exc:
            raise HTTPException(404, "报告不存在") from exc
        return Response(report["markdown"], media_type="text/markdown; charset=utf-8",
                        headers={"Content-Disposition": f'attachment; filename="report-{report_id}.md"'})

    @app.get("/{asset_path:path}")
    async def frontend(asset_path: str):
        root = (DOX_AGENT_ROOT / "frontend/dist").resolve()
        path = (root / (asset_path or "index.html")).resolve()
        if asset_path.startswith("api/") or not path.is_relative_to(root) or not path.is_file():
            raise HTTPException(404, "页面未构建或资源不存在；请在 frontend 执行 npm run build")
        # index.html must revalidate: after a rebuild its hashed asset names change, and a cached
        # page would reference deleted files. Hashed assets are content-addressed, so cache hard.
        if path.name == "index.html":
            headers = {"Cache-Control": "no-cache, must-revalidate"}
        else:
            headers = {"Cache-Control": "public, max-age=31536000, immutable"}
        return FileResponse(path, headers=headers)

    return app


app = create_app()
