"""Server-side task prompts: one shared baseline plus one file per task.

Prompts are server text configuration, not code; the first release has no template
management platform (demand §9.3). ``task4`` is declared here because a session may bind to
it, but its report body is generated by ``POST /api/reports``, never by the chat graph.
"""

from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BASE_FILE = "base.md"
DEFAULT_TASK_ID = "task1"
CHAT_TASK_IDS = ("task1", "task2", "task3", "task4")

TASKS: tuple[dict, ...] = (
    {"id": "task1", "name": "精准问答", "description": "基于本地文档回答具体问题，先给结论再逐条引用，不推测。",
     "output_hint": "结论 + 逐条 [n] 引用 + 资料范围与局限", "has_template": False, "file": "task1_qa.md"},
    {"id": "task2", "name": "对比分析", "description": "跨文档、项目或时间做对比，给出对比维度、差异结论与可比性前提。",
     "output_hint": "对比维度表 + 差异结论 + 可比性前提", "has_template": False, "file": "task2_compare.md"},
    {"id": "task3", "name": "趋势推测", "description": "基于本次样本讨论领域走向，事实与推断分段并标注样本范围与局限。",
     "output_hint": "事实/推断分段 + 方向性置信度 + 样本局限", "has_template": False, "file": "task3_trend.md"},
    {"id": "task4", "name": "专项报告", "description": "按模板生成可保存的结构化报告，走统一报告入口，不在聊天中生成正文。",
     "output_hint": "Markdown 报告 + 来源清单 + 局限", "has_template": True, "file": "task4_report.md",
     "intake_file": "task4_intake.md"},
)


class UnknownTaskError(ValueError):
    """Raised for a task id outside the fixed first-release set."""


@lru_cache(maxsize=None)
def _read(name: str) -> str:
    return (ROOT / name).read_text(encoding="utf-8").strip()


def _entry(task_id: str) -> dict:
    for task in TASKS:
        if task["id"] == task_id:
            return task
    raise UnknownTaskError(f"未知任务：{task_id}")


def base_prompt() -> str:
    """Hard constraints shared by every task."""
    return _read(BASE_FILE)


def task_prompt(task_id: str) -> str:
    """Task specific role, focus and output contract. Unknown ids raise, never fall back."""
    return _read(_entry(task_id)["file"])


def task_instruction(task_id: str, *, phase: str = "chat") -> str:
    """Baseline plus task prompt; the task part may narrow or open derivation, never the baseline.

    ``phase`` selects the task4 stage: ``chat`` uses the intake prompt (parameter collection, no
    report body); ``report`` uses the generation baseline. Other tasks ignore ``phase`` (§8.4 V4).
    """
    entry = _entry(task_id)
    if task_id == "task4" and phase == "chat":
        return base_prompt() + "\n\n" + _read(entry["intake_file"])
    return base_prompt() + "\n\n" + _read(entry["file"])


def list_tasks() -> list[dict]:
    return [{"id": t["id"], "name": t["name"], "description": t["description"],
             "output_hint": t.get("output_hint", ""), "has_template": t["has_template"]} for t in TASKS]
