"""Server-side task prompts: one shared baseline plus one file per task.

Prompts are server text configuration, not code; the first release has no template
management platform (demand §9.3). ``task4`` is declared here because a session may bind to
it, but its report body is generated by ``POST /api/reports``, never by the chat graph.
"""

from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TEMPLATES_DIR = ROOT.parent / "templates"
BASE_FILE = "base.md"
DEFAULT_TASK_ID = "task1"
CHAT_TASK_IDS = ("task1", "task2", "task3", "task4")
# Single authority for report section structure (§9.3); task4_report.md keeps only instructions.
REPORT_TEMPLATES = ("achievements", "hotspots", "future_directions", "comprehensive", "intelligence")
TEMPLATE_NAMES = {
    "achievements": "成果报告",
    "hotspots": "热点报告",
    "future_directions": "技术研判报告",
    "comprehensive": "综合报告",
    "intelligence": "情报分析报告",
}

TASKS: tuple[dict, ...] = (
    {"id": "task1", "name": "精准问答", "description": "基于本地文档回答具体问题，先给结论再逐条引用，不推测。",
     "example": "这批项目采用了哪些关键方法？",
     "output_hint": "结论 + 逐条 [n] 引用 + 资料范围与局限", "has_template": False, "file": "task1_qa.md",
     "artifacts": {"default": "text", "allowed": ["text"]}, "templates": []},
    {"id": "task2", "name": "对比分析", "description": "跨文档、项目或时间做对比，给出对比维度、差异结论与可比性前提。",
     "example": "比较这些项目的研究对象、方法和应用。",
     "output_hint": "对比维度表 + 差异结论 + 可比性前提", "has_template": False, "file": "task2_compare.md",
     "artifacts": {"default": "text", "allowed": ["text", "table"]}, "templates": []},
    {"id": "task3", "name": "技术研判", "description": "研判技术路线的成熟程度与后续工作，事实与研判意见分段并标注样本范围与局限。",
     "example": "这个领域有哪些研究路线，已经实现了哪些工作，还有哪些工作可以做？",
     "output_hint": "事实/研判分段 + 方向性置信度 + 样本局限", "has_template": False, "file": "task3_assess.md",
     "artifacts": {"default": "text", "allowed": ["text"]}, "templates": []},
    {"id": "task4", "name": "专项报告", "description": "按模板生成可保存的结构化报告，走统一报告入口，不在聊天中生成正文。",
     "example": "生成一份面上项目成果报告。",
     "output_hint": "Markdown 报告 + 来源清单 + 局限", "has_template": True, "file": "task4_report.md",
     "intake_file": "task4_intake.md",
     "artifacts": {"default": "document", "allowed": ["document"]}, "templates": list(REPORT_TEMPLATES)},
)


class UnknownTaskError(ValueError):
    """Raised for a task id outside the fixed first-release set."""


@lru_cache(maxsize=None)
def _read(name: str) -> str:
    return (ROOT / name).read_text(encoding="utf-8").strip()


def _entry(task_id: str) -> dict:
    for task in TASKS:
        if task["id"] == task_id:
            return task
    raise UnknownTaskError(f"未知任务：{task_id}")


def base_prompt() -> str:
    """Hard constraints shared by every task."""
    return _read(BASE_FILE)


def target_instruction() -> str:
    """Fixed extraction contract for the four-dimension target JSON."""
    return _read("target_extract.md")


def hierarchy_instruction() -> str:
    """Corpus-level synthesis contract: scenes, issues, tech routes and achievement aspects.

    The model may only name entries that already exist in the four-dimension topics;
    the caller drops anything that cannot be traced back (需求 §17).
    """
    return _read("hierarchy.md")


def topic_summary_instruction() -> str:
    """Per-topic grounded summary contract; every point cites input evidence refs (需求 §14.4)."""
    return _read("topic_summary.md")


def task_prompt(task_id: str) -> str:
    """Task specific role, focus and output contract. Unknown ids raise, never fall back."""
    return _read(_entry(task_id)["file"])


def report_template(template_id: str) -> str:
    """Report section structure from ``src/templates/<id>.md`` (single authority, §9.3)."""
    if template_id not in REPORT_TEMPLATES:
        raise UnknownTaskError(f"未知报告模板：{template_id}")
    return (TEMPLATES_DIR / f"{template_id}.md").read_text(encoding="utf-8").strip()


def task_instruction(task_id: str, *, phase: str = "chat") -> str:
    """Baseline plus task prompt; the task part may narrow or open derivation, never the baseline.

    ``phase`` selects the task4 stage: ``chat`` uses the intake prompt (parameter collection, no
    report body); ``report`` uses the generation baseline. Other tasks ignore ``phase`` (§8.4 V4).
    """
    entry = _entry(task_id)
    if task_id == "task4" and phase == "chat":
        return base_prompt() + "\n\n" + _read(entry["intake_file"])
    parts = [base_prompt(), _read(entry["file"])]
    if task_id in ("task2", "task3") or (task_id == "task4" and phase == "report"):
        parts.append(_read("target_facet_guide.md"))
    return "\n\n".join(parts)


def default_outline(task: dict) -> str:
    """Editable starting outline for a task copy (query 2026-1009 1541): goal, output, rules.

    The built-in prompt file stays the engine's fixed text; a user's outline is added after it
    and can refine the work, never replace citation or evidence rules.
    """
    output = "\n".join(f"- {part.strip()}" for part in task.get("output_hint", "").split("+") if part.strip())
    return (f"## 目标\n{task['description']}\n\n## 输出结构\n{output or '- 结论与依据'}\n\n"
            "## 要求\n- 只依据所选知识库资料，关键结论标注来源\n- 资料不足时说明缺口，不推测")


def list_tasks() -> list[dict]:
    return [{"id": t["id"], "name": t["name"], "description": t["description"],
             "example": t["example"],
             "output_hint": t.get("output_hint", ""), "has_template": t["has_template"],
             "artifacts": t["artifacts"], "templates": t["templates"],
             "outline": default_outline(t), "prompt": _read(t["file"])} for t in TASKS]


def list_templates() -> list[dict]:
    """Read-only catalogue of the built-in output templates, with their section outline."""
    return [{"id": template_id, "name": TEMPLATE_NAMES.get(template_id, template_id),
             "content": report_template(template_id)} for template_id in REPORT_TEMPLATES]


def compose_question_instruction() -> str:
    """Turns clicked task/element/intent keywords into one editable question."""
    return _read("compose_question.md")


def lineage_instruction() -> str:
    """Top two lineage levels (technology system › direction) over a corpus's technique items."""
    return _read("lineage.md")


def lineage_assign_instruction() -> str:
    """Per-batch placement of technique items into direction › theme, with a maturity level."""
    return _read("lineage_assign.md")
